App/forms/owncenter.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, RadioField
from wtforms.validators import DataRequired, NumberRange
from flask_wtf.file import FileAllowed, FileRequired, FileField
from App.extensions import file  # 导入文件上传配置对象


# 修改与查看个人信息的表单类
class UserInfo(FlaskForm):
    username = StringField('用户名', render_kw={'readonly': 'true'})
    sex = RadioField(label='性别', choices=[('1', '男'), ('0', '女')], validators=[DataRequired('性别必选')])
    age = IntegerField('年龄', validators=[DataRequired('年龄不能为空'), NumberRange(min=1, max=99, message='年龄在1~99之间')])
    email = StringField('邮箱', render_kw={'readonly': 'true'})
    lastLogin = StringField('上次登录时间', render_kw={'disabled': 'true'})
    register = StringField('注册时间', render_kw={'disabled': 'true'})
    submit = SubmitField('修改')


# 文件上传
class Upload(FlaskForm):
    icon = FileField('头像上传', validators=[FileRequired('您还没有选择上传的头像'),FileAllowed(file, message='该文件类型不允许上传')])
    submit = SubmitField('上传')

App/views/owncenter.py
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app

from App.models import Posts, Categorys
from App.forms import UserInfo  # 导入个人信息显示user模型类和文件上传表单类
from App.forms import SendPosts,Upload  # 用于编辑博客
from flask_login import current_user, login_required
from App.extensions import db, file, qiniu_store
import os
from App.extensions import file
from PIL import Image

owncenter = Blueprint('owncenter', __name__)


# 查看与修改个人信息
@owncenter.route('/user_info/', methods=['GET', 'POST'])
def user_info():
    form = UserInfo()
    if form.validate_on_submit():
        current_user.age = form.age.data

    form.username.data = current_user.username
    form.age.data = current_user.age
    form.sex.data = str(int(current_user.sex))
    form.email.data = current_user.email
    form.lastLogin.data = current_user.lastLogin
    form.register.data = current_user.registerTime
    return render_template('owncenter/user_info.html', form=form)


# 博客管理
@owncenter.route('/posts_manager/')
def posts_manager():
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    # 查询当前用户发表的所有博客，pid为0证明是博客内容，而不是评论和回复内容。state=0是所有人可见，
    # 按照时间进行降序查询
    posts = current_user.posts.filter_by(pid=0, state=0).order_by(Posts.timestamp.desc())
    # 获取page页面的数据
    pagination = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(Posts.timestamp.desc()) \
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据

    return render_template('owncenter/posts_manager.html', posts=posts, pagination=pagination)


# 博客删除
@owncenter.route('/del_posts/<int:pid>')
@login_required
def del_posts(pid):
    # 查询博客
    p = Posts.query.get(pid)
    # 判断该博客是否存在
    if p:
        # 执行删除
        flash('删除成功')
        p.delete()  # 删除博客内容
        comment = Posts.query.filter(Posts.path.contains(str(pid)))  # 删除评论和留言的内容
        for posts in comment:
            posts.delete()
    else:
        flash('您要删除的博客不存在')
    return redirect(url_for('owncenter.posts_manager'))


# 使用uuid扩展库生成唯一的名称
def random_filename(suffix):
    import uuid
    u = uuid.uuid4()
    return str(u) + '.' + suffix


# 图片缩放处理
def img_zoom(path, width=100, height=100):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    img.thumbnail((width, height))
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


#  头像上传
@owncenter.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = Upload()
    if form.validate_on_submit():
        icon = request.files.get('icon')  # 获取上传对象
        suffix = icon.filename.split('.')[-1]  # 获取后缀
        newName = random_filename(suffix)  # 获取新图片的名称
        # 以新名称保存图片
        file.save(icon, name=newName)
        delPath = current_app.config['UPLOADED_PHOTOS_DEST']
        # 删除之前上传的图片
        if current_user.icon != 'default.jpg':  # 如果不等于，则证明上传了头像
            os.remove(os.path.join(delPath, current_user.icon))
        current_user.icon = newName  # 更改当前对象的图片名称
        db.session.add(current_user)  # 更新到数据库中
        db.session.commit()
        # 拼接图片路径
        path = os.path.join(delPath, newName)
        # 进行缩放
        img_zoom(path)

    return render_template('owncenter/upload.html', form=form)


# 博客编辑
@owncenter.route('/edit_posts/<int:pid>', methods=['POST', 'GET'])
def edit_posts(pid):
    form = SendPosts()  # 实例化表单
    p = Posts.query.get(pid)  # 根据博客id  查询
    ctgs = Categorys.query.all()
    if not p:
        flash('该博客不存在')
        return redirect(url_for('owncenter.posts_manager'))
    if form.validate_on_submit():
        # md格式
        article = request.form['article']
        # 得到所选的分类值
        ctgs = request.form['ctgs']
        tags = Categorys.query.filter_by(categorys=ctgs).first()
        # 图片上传
        img = request.files.get('img')  # 获取上传对象
        ex = os.path.splitext(img.filename)[1]
        filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file = img.stream.read()
        qiniu_store.save(file, filename)

        p.title = form.title.data
        p.article = article
        p.img = qiniu_store.url(filename)
        p.tags = [tags]
        p.save()
        flash('博客更新成功')
        return redirect(url_for('owncenter.posts_manager'))
    form.title.data = p.title
    form.article.data = p.article

    return render_template('owncenter/edit_posts.html', form=form, ctgs=ctgs)

App/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from sqlalchemy import or_

from App.forms import SendPosts, Comment, Catgs  # 导入发表博客与发表评论的表单类
from App.models import Posts,Categorys,User # 导入博客模型类和标签模型类
from flask_login import current_user, login_required

from datetime import datetime
from flask import jsonify, request
from App.extensions import qiniu_store, csrf
import os, base64
from App.extensions import file
from PIL import Image

posts = Blueprint('posts', __name__)


# 使用uuid扩展库生成唯一的名称
def random_filename(suffix):
    import uuid
    u = uuid.uuid4()
    return str(u) + '.' + suffix


# 图片缩放处理
def img_zoom(path, width=1000, height=250):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    # img.thumbnail((width, height))
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


@posts.route('/send_posts/', methods=['GET', 'POST'])
def send_posts():
    form = SendPosts()
    ctgs = Categorys.query.all()
    # 判断登录后在进行发表
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再发表')
    if current_user.id==1:
        if form.validate_on_submit():
            # md格式
            article = request.form['article']
            ctgs = request.form['ctgs']
            tags = Categorys.query.filter_by(categorys=ctgs).first()
            # 图片上传
            img = request.files.get('img')  # 获取上传对象
            ex = os.path.splitext(img.filename)[1]
            filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
            file = img.stream.read()
            qiniu_store.save(file, filename)
            post = Posts(title=form.title.data, user=current_user, article=article, img=qiniu_store.url(filename),tags=[tags])
            post.save()
            flash('博客发表成功')
            return redirect(url_for('main.index'))
    else:
        flash('您没有发表博客的权限！')
        return redirect(url_for('main.index'))
    return render_template('posts/send_posts.html', form=form, ctgs=ctgs)


# 增加分类
@posts.route('/add_catgs/', methods=['GET', 'POST'])
def add_catgs():
    form = Catgs()
    ctgs = Categorys.query.all()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        catgs = Categorys(categorys=form.categorys.data)
        catgs.save()
        print(form.categorys.data)
        flash('分类添加成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/add_categorys.html', form=form, ctgs=ctgs)


# 删除分类
@posts.route('/delete_catgs/', methods=['GET', 'POST'])
def delete_catgs():
    ctgs = Categorys.query.all()
    form = Catgs()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        cs = request.form['ctgs']
        d = Categorys.query.filter_by(categorys=cs)[0]
        d.delete()
        flash('分类删除成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/delete_categorys.html', form=form, ctgs=ctgs)


# 搜索
@posts.route('/search/', methods=['GET', 'POST'])
@csrf.exempt
def search():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    # 获取搜索的关键字
    if request.method == 'POST':
        keyword = request.form.get('keyword', '')
    else:
        keyword = request.args.get('keyword', '')
    # 查询pid为0（是博客内容，不为0则是评论或回复内容），statue为0（所有人可见），按照时间降序显示
    # 搜索功能，搜索内容为：标题或正文
    pagination = Posts.query.filter(or_(Posts.title.contains(keyword), Posts.article.contains(keyword)), Posts.pid == 0,
                                    Posts.state == 0) \
        .order_by(Posts.timestamp.desc()) \
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]
    return render_template('posts/search_detail.html', pagination=pagination, posts=data, keyword=keyword,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客分类
@posts.route('posts_ctgs',methods=['GET','POST'])
def posts_ctgs():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    cid = request.args.get('pid')
    global pagination,data
    posts = Categorys.query.get(cid)
    for i in posts.posts:
        pagination = Posts.query.filter(Posts.title==i.title).order_by(Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
        data = pagination.items  # 获取page页面的数据
    category = Categorys.query.get(cid)
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]

    return render_template('posts/posts_ctgs.html',pagination=pagination,posts=data,category=category,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客详情
@posts.route('/posts_detail/<int:pid>/')
def posts_detail(pid):
    # 查询当前博客的内容 pid为博客的自增id 并不是博客模型字段的pid
    p = Posts.query.get(pid)
    p.visit += 1  # 博客的访问量
    p.save()
    form = Comment()  # 发表评论和回复的表单类
    # 查询出博客的评论内容和回复，按照博客内容和回复在一起的排序顺序，
    # 过滤条件为博客path中包含博客id的，这样博客就将博客的内容过滤出去，只查询评论和留言
    comment = Posts.query.filter(Posts.path.contains(str(pid))).order_by(Posts.path.concat(Posts.id))
    ctgs = Categorys.query.all()
    comment_nums = Posts.query.filter(Posts.path.contains(str(pid))).count()

    return render_template('posts/posts_detail.html', posts=p, form=form, comment=comment, ctgs=ctgs, comment_nums=comment_nums)


# 评论和回复
@posts.route('/comment/', methods=['GET', 'POST'])
@login_required
def comment():
    pid = request.form.get('pid')
    rid = request.form.get('rid')
    # 判断当前是评论还是回复，如果为评论则为假，否则为真
    if rid:
        id = rid
    else:
        id = pid
    p = Posts.query.get(int(id))
    Posts(article=request.form.get('article'), pid=id, path=p.path + id + ',', user=current_user).save()

    return redirect(url_for('posts.posts_detail', pid=pid))


# editor.md的图片上传
@posts.route('/upload_image/', methods=['POST'])
@login_required
@csrf.exempt
def upload_image():
    data = request.files.get('editormd-image-file')
    if not data:
        res = {
            'success': 0,
            'message': '图片失败请重试'
        }
    else:
        ex = os.path.splitext(data.filename)[1]
        filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file = data.stream.read()
        qiniu_store.save(file, filename)
        res = {
            'success': 1,
            'message': '图片上传成功',
            'url': qiniu_store.url(filename)
        }
    return jsonify(res)

App/templates/owncenter/edit_posts.html
{% extends 'common/base1.0.html' %}
{% block title %}
    修改博客
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
{% endblock %}

{% block scripts %}
    {{ super() }}

{% endblock %}
{% block page_content %}
    <div style="background-color: rgba(255,255,255,0.5);padding: 5px 3px">
<h2 class="page-header">修改博客</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
    {# 标题 #}
        {{ form.title.label(style='font-size:16px;') }}
        {{ form.title(class='form-control') }}
        {% for err in form.title.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
    <br>
    {# 分类 #}
    <div>
       <P> <font style="font-size: 20px">分类</font> &nbsp;&nbsp;&nbsp;<a type="submit" class="btn btn-success" href="{{ url_for('posts.add_catgs', _exrernal=True) }}">添加</a>
    &nbsp;&nbsp;&nbsp;</P>


        <div class="checkbox" style="position: relative;left: 20px">
            {% for ctg in ctgs %}
            <label >
                <input type="checkbox" style="height: 20px" name="ctgs" value="{{ ctg.categorys }}"><font style="font-size: 20px">{{ ctg.categorys }} </font>
            </label>
            {% endfor %}
        </div>

    </div>
{# 图片上传 #}
<div>
    <hr>
        图片上传：<input type="file" name="img" required>
    <br>
</div>
    <br>
    {# 正文 #}
        {{ form.article.label(style='font-size:16px;') }}
        <div id="test-editormd" class="editormd">
        {{ form.article(style="display:none;") }}
        </div>


        {% for err in form.article.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">发表</button>
    </form>
    </div>
{% endblock %}

App/templates/owncenter/posts_manager.html
{% extends 'common/base1.0.html' %}
{% block title %}
    博客管理
{% endblock %}

{% block page_content %}
    <div style="background-color: rgba(255,255,255,0.5);padding: 5px 5px">
    <h2 class="page-header">博客管理</h2>
    <form class="form-inline definewidth m20" action="index.html" method="get">
        <button type="button" class="btn btn-success" id="addnew" onclick="window.location.href={{ url_for('posts.send_posts') }}">新增博客</button>
    </form>
    <br>
    <table class="table table-bordered table-hover definewidth m10">
        <thead>
        <tr>
            <th>id</th>
            <th>标题</th>
            <th>博客内容</th>
            <th>浏览量</th>
            <th>是否所有人可见</th>
            <th>发表时间</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for row in posts %}
        <tr>
            <td>{{ loop.revindex }}</td>
            <td>{{ row.title }}</td>
            <td>{{ row.article|striptags|showEllipsis(20) }}</td>
            <td>{{ row.visit }}次</td>
            <td>
                {% if row.state %}
                    仅自己可见
                {% else %}
                    所有人可见
                {% endif %}
            </td>
            <td>{{ moment(row.timestamp).format('YYYY-MM-DD H:m:s') }}</td>
            <td>
                <a href="{{ url_for('owncenter.edit_posts',pid=row.id) }}" target="_blank">编辑</a> |
                <a href="{{ url_for('owncenter.del_posts',pid=row.id) }}" >删除</a> |
                <a href="{{ url_for('posts.posts_detail',pid=row.id) }}" target="_blank">查看</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    </div>
    {# 分页 #}
{#    {% from 'common/page_macro.html' import page %}#}
{#    {{ page(pagination, 'owncenter.posts_manager') }}#}
{% endblock %}

App/templates/owncenter/upload.html
{% extends 'common/base1.0.html' %}
{% block title %}
    头像上传
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block page_content %}
<h2 class="page-header">头像上传</h2>
    <img src="{{ url_for('static',filename='upload/'+current_user.icon) }}" alt="" width="200" style="border-radius:10px;">
    <hr>
    {{ quick_form(form) }}
    <br>
{% endblock %}

App/templates/owncenter/user_info.html
{% extends 'common/base1.0.html' %}
{% block title %}
    查看个人信息
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block page_content %}
    <h2 class="page-header">查看与修改个人信息</h2>
    <div class="row">
        <div class="col-md-8"><img src="{{ url_for('static',filename='img/b.jpg', _external=True) }}" width="700px" height="450px"></div>
      <div class="col-md-4">{{ quick_form(form) }}</div>
    </div>
    <br>
{% endblock %}