App/views/main.py
from flask import Blueprint,render_template, request,current_app

from App.models import Posts,Categorys
from sqlalchemy import func

main = Blueprint('main', __name__)


# 首页视图
@main.route('/')
@main.route('/index/')
def index():
    try:
        page = int(request.args.get('page',1))
    except:
        page = 1
    # 查询pid为0（是博客内容，不为0则是评论或回复内容），statue为0（所有人可见），按照时间降序显示
    pagination = Posts.query.filter(Posts.pid==0, Posts.state==0).order_by(Posts.timestamp.desc())\
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]


    return render_template('main/index.html', posts=data, pagination=pagination, art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)

App/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from sqlalchemy import or_

from App.forms import SendPosts, Comment, Catgs  # 导入发表博客与发表评论的表单类
from App.models import Posts,Categorys,User # 导入博客模型类和标签模型类
from flask_login import current_user, login_required

from datetime import datetime
from flask import jsonify, request
from App.extensions import qiniu_store, csrf
import os, base64
from App.extensions import file
from PIL import Image

posts = Blueprint('posts', __name__)


# 使用uuid扩展库生成唯一的名称
def random_filename(suffix):
    import uuid
    u = uuid.uuid4()
    return str(u) + '.' + suffix


# 图片缩放处理
def img_zoom(path, width=1000, height=250):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    # img.thumbnail((width, height))
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


@posts.route('/send_posts/', methods=['GET', 'POST'])
def send_posts():
    form = SendPosts()
    ctgs = Categorys.query.all()
    # 判断登录后在进行发表
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再发表')
    if current_user.id==1:
        if form.validate_on_submit():
            # md格式
            article = request.form['article']
            ctgs = request.form['ctgs']
            tags = Categorys.query.filter_by(categorys=ctgs).first()
            # 图片上传
            img = request.files.get('img')  # 获取上传对象
            ex = os.path.splitext(img.filename)[1]
            filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
            file = img.stream.read()
            qiniu_store.save(file, filename)
            post = Posts(title=form.title.data, user=current_user, article=article, img=qiniu_store.url(filename),tags=[tags])
            post.save()
            flash('博客发表成功')
            return redirect(url_for('main.index'))
    else:
        flash('您没有发表博客的权限！')
        return redirect(url_for('main.index'))
    return render_template('posts/send_posts.html', form=form, ctgs=ctgs)


# 增加分类
@posts.route('/add_catgs/', methods=['GET', 'POST'])
def add_catgs():
    form = Catgs()
    ctgs = Categorys.query.all()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        catgs = Categorys(categorys=form.categorys.data)
        catgs.save()
        print(form.categorys.data)
        flash('分类添加成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/add_categorys.html', form=form, ctgs=ctgs)


# 删除分类
@posts.route('/delete_catgs/', methods=['GET', 'POST'])
def delete_catgs():
    ctgs = Categorys.query.all()
    form = Catgs()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        cs = request.form['ctgs']
        d = Categorys.query.filter_by(categorys=cs)[0]
        d.delete()
        flash('分类删除成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/delete_categorys.html', form=form, ctgs=ctgs)


# 搜索
@posts.route('/search/', methods=['GET', 'POST'])
@csrf.exempt
def search():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    # 获取搜索的关键字
    if request.method == 'POST':
        keyword = request.form.get('keyword', '')
    else:
        keyword = request.args.get('keyword', '')
    # 查询pid为0（是博客内容，不为0则是评论或回复内容），statue为0（所有人可见），按照时间降序显示
    # 搜索功能，搜索内容为：标题或正文
    pagination = Posts.query.filter(or_(Posts.title.contains(keyword), Posts.article.contains(keyword)), Posts.pid == 0,
                                    Posts.state == 0) \
        .order_by(Posts.timestamp.desc()) \
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]
    return render_template('posts/search_detail.html', pagination=pagination, posts=data, keyword=keyword,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客分类
@posts.route('posts_ctgs',methods=['GET','POST'])
def posts_ctgs():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    cid = request.args.get('pid')
    global pagination,data
    posts = Categorys.query.get(cid)
    for i in posts.posts:
        pagination = Posts.query.filter(Posts.title==i.title).order_by(Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
        data = pagination.items  # 获取page页面的数据
    category = Categorys.query.get(cid)
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]

    return render_template('posts/posts_ctgs.html',pagination=pagination,posts=data,category=category,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客详情
@posts.route('/posts_detail/<int:pid>/')
def posts_detail(pid):
    # 查询当前博客的内容 pid为博客的自增id 并不是博客模型字段的pid
    p = Posts.query.get(pid)
    p.visit += 1  # 博客的访问量
    p.save()
    form = Comment()  # 发表评论和回复的表单类
    # 查询出博客的评论内容和回复，按照博客内容和回复在一起的排序顺序，
    # 过滤条件为博客path中包含博客id的，这样博客就将博客的内容过滤出去，只查询评论和留言
    comment = Posts.query.filter(Posts.path.contains(str(pid))).order_by(Posts.path.concat(Posts.id))
    ctgs = Categorys.query.all()
    comment_nums = Posts.query.filter(Posts.path.contains(str(pid))).count()

    return render_template('posts/posts_detail.html', posts=p, form=form, comment=comment, ctgs=ctgs, comment_nums=comment_nums)


# 评论和回复
@posts.route('/comment/', methods=['GET', 'POST'])
@login_required
def comment():
    pid = request.form.get('pid')
    rid = request.form.get('rid')
    # 判断当前是评论还是回复，如果为评论则为假，否则为真
    if rid:
        id = rid
    else:
        id = pid
    p = Posts.query.get(int(id))
    Posts(article=request.form.get('article'), pid=id, path=p.path + id + ',', user=current_user).save()

    return redirect(url_for('posts.posts_detail', pid=pid))


# editor.md的图片上传
@posts.route('/upload_image/', methods=['POST'])
@login_required
@csrf.exempt
def upload_image():
    data = request.files.get('editormd-image-file')
    if not data:
        res = {
            'success': 0,
            'message': '图片失败请重试'
        }
    else:
        ex = os.path.splitext(data.filename)[1]
        filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file = data.stream.read()
        qiniu_store.save(file, filename)
        res = {
            'success': 1,
            'message': '图片上传成功',
            'url': qiniu_store.url(filename)
        }
    return jsonify(res)

App/templates/main/index11111111.html
{% extends 'common/base.html' %}
{% block title %}
    首页
{% endblock %}

{% block scripts %}
{{ super() }}

{% endblock %}

{% block page_content %}
<div class="row" style="background-color:rgba(255,255,255,0.3);">
<div class="col-xs-6 col-md-3" style="top: 20px">
        <img src="{{ url_for('static',filename='img/tou.jpg',_external=True) }}" style="height:150px;border-radius: 80px;position: relative;left: 55px">
        <div style="font-size: 20px;">
            <p>&nbsp;&nbsp;A l o n e</p>
            <p>&nbsp;&nbsp;邮箱 :alone_3@163.com</p>
            <p></p>
            <p>&nbsp;&nbsp;文章：{{ art }}   篇</p>
            <p>&nbsp;&nbsp;访问量：{{ v }}</p>
        </div>
          <div class="http" style="background-color: rgba(255,255,255,0.8) ;border-radius: 5px;padding: 5px 5px;">
            <p style="font-size: 20px;background-color: rgba(255,255,255,1) ;border-radius: 10px;">&nbsp;&nbsp;点击排行:</p>
              {% for v in visit %}
               <ul>
                  <li><a href="{{ url_for('posts.posts_detail',pid=v.id, _external=True) }}" style="color: #00a8c6 ">{{ v.title }}</a></li>
              </ul>
              {% endfor %}
          </div>
  <br>
          <div class="http" style="background-color: rgba(255,255,255,0.8) ;border-radius: 10px;padding: 5px 5px;">
            <p style="font-size: 20px;background-color: rgba(255,255,255,1) ;border-radius: 10px;">&nbsp;&nbsp;分类:</p>
              {% for c in ctgs %}
                  <h5 style="position:relative;left: 10px"><a href="{{ url_for('posts.posts_ctgs',pid=c.id) }}" style="color: #7F007F">{{ c.categorys }} <span class="label label-default"></span></a></h5>
              {% endfor %}
          </div>
      <br>
          <div class="http" style="background-color: rgba(255,255,255,0.8) ;border-radius: 5px;">
            <p style="font-size: 20px;background-color: rgba(255,255,255,1) ;border-radius: 10px;">&nbsp;&nbsp;友情链接:</p>
            <a style="font-size: 15px;position:relative;left: 20px" href="http://alonezd.top">小雕个人博客</a>
          </div>
</div>
<div class="col-xs-12 col-md-9">
    {# 轮播图 #}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for i in range(1,4) %}
                <div class="item {% if i==1 %}active{% endif %} ">
                    <img src="{{ url_for('static',filename='img/lunbo/'+i|string+'.jpg') }}" alt="..." width="1500px"
                         style="height: 450px; margin: auto;">
                    <div class="carousel-caption" style="color: orange">
                        A l o n e ' s   b l o g
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {# 博客内容的展示 #}
    {% for p in posts %}
    <div class="media">
    <a href="{{ url_for('posts.posts_detail',pid=p.id, _external=True) }}" style="color: #000000;text-decoration: none">
        <div class="media-left media-middle">
                <img class="media-object" src="{{ url_for('static',filename='upload/'+p.img) }}" alt="..."   style="border-radius: 5px;border-top:2px solid #ccc;border-right:2px solid #ccc;">
        </div>
        <div class="media-body">
            <h4 class="media-heading" style="font-weight: bold">{{ p.title }}</h4>
            <span style="font-size: 18px">{{ p.article|safe|striptags|showEllipsis }}</span>
            <br>
        </div>
            <div style="float: right;color: black;font-size: 15px">
                <b>👍:{{ p.visit }}</b>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {{moment(p.timestamp).format('YYYY-MM-DD H:m:s')}}
            </div>

    </a>
    </div>

        {% endfor %}
    {# 分页 #}
    {% from 'common/page_macro.html' import page %}
    {{ page(pagination, 'main.index') }}
    </div>
</div>
{% endblock %}

App/templates/main/index_1.0.html
{% extends 'common/base1.0.html' %}
{% block title %}
    首页
{% endblock %}

{% block scripts %}
{{ super() }}

{% endblock %}

{% block page_content %}
<div class="row" style="background-color:rgba(255,255,255,0.3);">
<div class="col-xs-6 col-md-3" style="top: 20px">
        <img src="{{ url_for('static',filename='img/tou.jpg',_external=True) }}" style="height:150px;border-radius: 80px;position: relative;left: 55px">
        <div style="font-size: 20px;">
            <p>&nbsp;&nbsp;A l o n e</p>
            <p>&nbsp;&nbsp;邮箱 :alone_3@163.com</p>
            <p></p>
            <p>&nbsp;&nbsp;文章：{{ art }}   篇</p>
            <p>&nbsp;&nbsp;访问量：{{ v }}</p>
        </div>
          <div class="http" style="background-color: rgba(255,255,255,0.8) ;border-radius: 5px;padding: 5px 5px;">
            <p style="font-size: 20px;background-color: rgba(255,255,255,1) ;border-radius: 10px;">&nbsp;&nbsp;点击排行:</p>
              {% for v in visit %}
               <ul>
                  <li><a href="{{ url_for('posts.posts_detail',pid=v.id, _external=True) }}" style="color: #00a8c6 ">{{ v.title }}</a></li>
              </ul>
              {% endfor %}
          </div>
  <br>
          <div class="http" style="background-color: rgba(255,255,255,0.8) ;border-radius: 10px;padding: 5px 5px;">
            <p style="font-size: 20px;background-color: rgba(255,255,255,1) ;border-radius: 10px;">&nbsp;&nbsp;分类:</p>
              {% for c in ctgs %}
                  <h5 style="position:relative;left: 10px"><a href="{{ url_for('posts.posts_ctgs',pid=c.id) }}" style="color: #7F007F">{{ c.categorys }} <span class="label label-default"></span></a></h5>
              {% endfor %}
          </div>
      <br>
          <div class="http" style="background-color: rgba(255,255,255,0.8) ;border-radius: 5px;">
            <p style="font-size: 20px;background-color: rgba(255,255,255,1) ;border-radius: 10px;">&nbsp;&nbsp;友情链接:</p>
            <a style="font-size: 15px;position:relative;left: 20px" href="http://alonezd.top">小雕个人博客</a>
          </div>
</div>
<div class="col-xs-12 col-md-9">
    {# 轮播图 #}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for i in range(1,4) %}
                <div class="item {% if i==1 %}active{% endif %} ">
                    <img src="{{ url_for('static',filename='img/lunbo/'+i|string+'.jpg') }}" alt="..." width="1500px"
                         style="height: 450px; margin: auto;">
                    <div class="carousel-caption" style="color: orange">
                        A l o n e ' s   b l o g
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {# 博客内容的展示 #}
    {% for p in posts %}
    <div class="media">
    <a href="{{ url_for('posts.posts_detail',pid=p.id, _external=True) }}" style="color: #000000;text-decoration: none">
        <div class="media-left media-middle">
                <img class="media-object" src="{{ url_for('static',filename='upload/'+p.img) }}" alt="..."   style="border-radius: 5px;border-top:2px solid #ccc;border-right:2px solid #ccc;">
        </div>
        <div class="media-body">
            <h4 class="media-heading" style="font-weight: bold">{{ p.title }}</h4>
            <span style="font-size: 18px">{{ p.article|safe|striptags|showEllipsis }}</span>
            <br>
        </div>
            <div style="float: right;color: black;font-size: 15px">
                <b>👍:{{ p.visit }}</b>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {{moment(p.timestamp).format('YYYY-MM-DD H:m:s')}}
            </div>

    </a>
    </div>

        {% endfor %}
    {# 分页 #}
    {% from 'common/page_macro.html' import page %}
    {{ page(pagination, 'main.index') }}
    </div>
</div>
{% endblock %}