App/views/main.py
from flask import Blueprint,render_template, request,current_app

from App.models import Posts,Categorys
from sqlalchemy import func

main = Blueprint('main', __name__)


# 首页视图
@main.route('/')
@main.route('/index/')
def index():
    try:
        page = int(request.args.get('page',1))
    except:
        page = 1
    # 查询pid为0（是博客内容，不为0则是评论或回复内容），statue为0（所有人可见），按照时间降序显示
    pagination = Posts.query.filter(Posts.pid==0, Posts.state==0).order_by(Posts.timestamp.desc())\
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]


    return render_template('main/index.html', posts=data, pagination=pagination, art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)

App/views/owncenter.py
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app

from App.models import Posts, Categorys
from App.forms import UserInfo  # 导入个人信息显示user模型类和文件上传表单类
from App.forms import SendPosts,Upload  # 用于编辑博客
from flask_login import current_user, login_required
from App.extensions import db, file, qiniu_store
import os
from App.extensions import file
from PIL import Image

owncenter = Blueprint('owncenter', __name__)


# 查看与修改个人信息
@owncenter.route('/user_info/', methods=['GET', 'POST'])
def user_info():
    form = UserInfo()
    if form.validate_on_submit():
        current_user.age = form.age.data

    form.username.data = current_user.username
    form.age.data = current_user.age
    form.sex.data = str(int(current_user.sex))
    form.email.data = current_user.email
    form.lastLogin.data = current_user.lastLogin
    form.register.data = current_user.registerTime
    return render_template('owncenter/user_info.html', form=form)


# 博客管理
@owncenter.route('/posts_manager/')
def posts_manager():
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    # 查询当前用户发表的所有博客，pid为0证明是博客内容，而不是评论和回复内容。state=0是所有人可见，
    # 按照时间进行降序查询
    posts = current_user.posts.filter_by(pid=0, state=0).order_by(Posts.timestamp.desc())
    # 获取page页面的数据
    pagination = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(Posts.timestamp.desc()) \
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据

    return render_template('owncenter/posts_manager.html', posts=posts, pagination=pagination)


# 博客删除
@owncenter.route('/del_posts/<int:pid>')
@login_required
def del_posts(pid):
    # 查询博客
    p = Posts.query.get(pid)
    # 判断该博客是否存在
    if p:
        # 执行删除
        flash('删除成功')
        p.delete()  # 删除博客内容
        comment = Posts.query.filter(Posts.path.contains(str(pid)))  # 删除评论和留言的内容
        for posts in comment:
            posts.delete()
    else:
        flash('您要删除的博客不存在')
    return redirect(url_for('owncenter.posts_manager'))


# 使用uuid扩展库生成唯一的名称
def random_filename(suffix):
    import uuid
    u = uuid.uuid4()
    return str(u) + '.' + suffix


# 图片缩放处理
def img_zoom(path, width=100, height=100):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    img.thumbnail((width, height))
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


#  头像上传
@owncenter.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = Upload()
    if form.validate_on_submit():
        icon = request.files.get('icon')  # 获取上传对象
        suffix = icon.filename.split('.')[-1]  # 获取后缀
        newName = random_filename(suffix)  # 获取新图片的名称
        # 以新名称保存图片
        file.save(icon, name=newName)
        delPath = current_app.config['UPLOADED_PHOTOS_DEST']
        # 删除之前上传的图片
        if current_user.icon != 'default.jpg':  # 如果不等于，则证明上传了头像
            os.remove(os.path.join(delPath, current_user.icon))
        current_user.icon = newName  # 更改当前对象的图片名称
        db.session.add(current_user)  # 更新到数据库中
        db.session.commit()
        # 拼接图片路径
        path = os.path.join(delPath, newName)
        # 进行缩放
        img_zoom(path)

    return render_template('owncenter/upload.html', form=form)


# 博客编辑
@owncenter.route('/edit_posts/<int:pid>', methods=['POST', 'GET'])
def edit_posts(pid):
    form = SendPosts()  # 实例化表单
    p = Posts.query.get(pid)  # 根据博客id  查询
    ctgs = Categorys.query.all()
    if not p:
        flash('该博客不存在')
        return redirect(url_for('owncenter.posts_manager'))
    if form.validate_on_submit():
        # md格式
        article = request.form['article']
        # 得到所选的分类值
        ctgs = request.form['ctgs']
        tags = Categorys.query.filter_by(categorys=ctgs).first()
        # 图片上传
        img = request.files.get('img')  # 获取上传对象
        ex = os.path.splitext(img.filename)[1]
        filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file = img.stream.read()
        qiniu_store.save(file, filename)

        p.title = form.title.data
        p.article = article
        p.img = qiniu_store.url(filename)
        p.tags = [tags]
        p.save()
        flash('博客更新成功')
        return redirect(url_for('owncenter.posts_manager'))
    form.title.data = p.title
    form.article.data = p.article

    return render_template('owncenter/edit_posts.html', form=form, ctgs=ctgs)

App/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from sqlalchemy import or_

from App.forms import SendPosts, Comment, Catgs  # 导入发表博客与发表评论的表单类
from App.models import Posts,Categorys,User # 导入博客模型类和标签模型类
from flask_login import current_user, login_required

from datetime import datetime
from flask import jsonify, request
from App.extensions import qiniu_store, csrf
import os, base64
from App.extensions import file
from PIL import Image

posts = Blueprint('posts', __name__)


# 使用uuid扩展库生成唯一的名称
def random_filename(suffix):
    import uuid
    u = uuid.uuid4()
    return str(u) + '.' + suffix


# 图片缩放处理
def img_zoom(path, width=1000, height=250):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    # img.thumbnail((width, height))
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


@posts.route('/send_posts/', methods=['GET', 'POST'])
def send_posts():
    form = SendPosts()
    ctgs = Categorys.query.all()
    # 判断登录后在进行发表
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再发表')
    if current_user.id==1:
        if form.validate_on_submit():
            # md格式
            article = request.form['article']
            ctgs = request.form['ctgs']
            tags = Categorys.query.filter_by(categorys=ctgs).first()
            # 图片上传
            img = request.files.get('img')  # 获取上传对象
            ex = os.path.splitext(img.filename)[1]
            filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
            file = img.stream.read()
            qiniu_store.save(file, filename)
            post = Posts(title=form.title.data, user=current_user, article=article, img=qiniu_store.url(filename),tags=[tags])
            post.save()
            flash('博客发表成功')
            return redirect(url_for('main.index'))
    else:
        flash('您没有发表博客的权限！')
        return redirect(url_for('main.index'))
    return render_template('posts/send_posts.html', form=form, ctgs=ctgs)


# 增加分类
@posts.route('/add_catgs/', methods=['GET', 'POST'])
def add_catgs():
    form = Catgs()
    ctgs = Categorys.query.all()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        catgs = Categorys(categorys=form.categorys.data)
        catgs.save()
        print(form.categorys.data)
        flash('分类添加成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/add_categorys.html', form=form, ctgs=ctgs)


# 删除分类
@posts.route('/delete_catgs/', methods=['GET', 'POST'])
def delete_catgs():
    ctgs = Categorys.query.all()
    form = Catgs()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        cs = request.form['ctgs']
        d = Categorys.query.filter_by(categorys=cs)[0]
        d.delete()
        flash('分类删除成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/delete_categorys.html', form=form, ctgs=ctgs)


# 搜索
@posts.route('/search/', methods=['GET', 'POST'])
@csrf.exempt
def search():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    # 获取搜索的关键字
    if request.method == 'POST':
        keyword = request.form.get('keyword', '')
    else:
        keyword = request.args.get('keyword', '')
    # 查询pid为0（是博客内容，不为0则是评论或回复内容），statue为0（所有人可见），按照时间降序显示
    # 搜索功能，搜索内容为：标题或正文
    pagination = Posts.query.filter(or_(Posts.title.contains(keyword), Posts.article.contains(keyword)), Posts.pid == 0,
                                    Posts.state == 0) \
        .order_by(Posts.timestamp.desc()) \
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]
    return render_template('posts/search_detail.html', pagination=pagination, posts=data, keyword=keyword,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客分类
@posts.route('posts_ctgs',methods=['GET','POST'])
def posts_ctgs():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    cid = request.args.get('pid')
    global pagination,data
    posts = Categorys.query.get(cid)
    for i in posts.posts:
        pagination = Posts.query.filter(Posts.title==i.title).order_by(Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
        data = pagination.items  # 获取page页面的数据
    category = Categorys.query.get(cid)
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]

    return render_template('posts/posts_ctgs.html',pagination=pagination,posts=data,category=category,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客详情
@posts.route('/posts_detail/<int:pid>/')
def posts_detail(pid):
    # 查询当前博客的内容 pid为博客的自增id 并不是博客模型字段的pid
    p = Posts.query.get(pid)
    p.visit += 1  # 博客的访问量
    p.save()
    form = Comment()  # 发表评论和回复的表单类
    # 查询出博客的评论内容和回复，按照博客内容和回复在一起的排序顺序，
    # 过滤条件为博客path中包含博客id的，这样博客就将博客的内容过滤出去，只查询评论和留言
    comment = Posts.query.filter(Posts.path.contains(str(pid))).order_by(Posts.path.concat(Posts.id))
    ctgs = Categorys.query.all()
    comment_nums = Posts.query.filter(Posts.path.contains(str(pid))).count()

    return render_template('posts/posts_detail.html', posts=p, form=form, comment=comment, ctgs=ctgs, comment_nums=comment_nums)


# 评论和回复
@posts.route('/comment/', methods=['GET', 'POST'])
@login_required
def comment():
    pid = request.form.get('pid')
    rid = request.form.get('rid')
    # 判断当前是评论还是回复，如果为评论则为假，否则为真
    if rid:
        id = rid
    else:
        id = pid
    p = Posts.query.get(int(id))
    Posts(article=request.form.get('article'), pid=id, path=p.path + id + ',', user=current_user).save()

    return redirect(url_for('posts.posts_detail', pid=pid))


# editor.md的图片上传
@posts.route('/upload_image/', methods=['POST'])
@login_required
@csrf.exempt
def upload_image():
    data = request.files.get('editormd-image-file')
    if not data:
        res = {
            'success': 0,
            'message': '图片失败请重试'
        }
    else:
        ex = os.path.splitext(data.filename)[1]
        filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file = data.stream.read()
        qiniu_store.save(file, filename)
        res = {
            'success': 1,
            'message': '图片上传成功',
            'url': qiniu_store.url(filename)
        }
    return jsonify(res)

App/views/user.py
from flask import Blueprint,render_template,flash,url_for,redirect
from App.forms import Register, Login, AgainActive  # 导入表单注册类
from App.models import User  # 导入User模型类
from App.email import send_mail  # 导入发送邮件的函数
from flask_login import login_required, logout_user, login_user, current_user
from datetime import datetime


user = Blueprint('user', __name__)


@user.route('/register/', methods=['GET', 'POST'])
def register():
    # 实例化注册表单类
    form = Register()
    if form.validate_on_submit():
        # 实例化存储注册表单数据
        u = User(username=form.username.data, password=form.userpass.data,email=form.email.data)
        u.save()
        # 调用获取token的方法
        token = u.generate_token()
        # 发送邮件激活
        send_mail('账户激活', form.email.data,username=form.username.data, token=token)
        flash('注册成功，请前去邮箱激活')
        # 成功去登录
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)


# 进行账户激活的视图
@user.route('/active/<token>')
def active(token):
    if User.check_token(token):
        flash('激活成功，请前去登录...')
        # 激活成功跳转到登录
        return redirect(url_for('user.login'))
    else:
        flash('激活失败，请重新进行账户激活操作....')
        return redirect(url_for('user.again_active'))


# 再次激活的视图
@user.route('/again_active/',methods=['GET', 'POST'])
def again_active():
    form = AgainActive()
    if form.is_submitted():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('请输入正确的用户名或密码....')
        elif not u.check_password(form.userpass.data):
            flash('请输入正确的用户名或密码')
        elif not u.confirm:
            # 调用获取token的方法
            token = u.generate_token()
            # 发送邮件激活
            send_mail('账户再次激活', u.email,tem='again_active', username=form.username.data, token=token)
            flash('激活邮件发送成功，请前去邮箱激活')
        else:
            flash('该账户已经激活，请前去登录...')
    return render_template('user/again_active.html', form=form)


# 登录视图
@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('请输入正确的用户名或密码')
        elif not u.confirm:
            flash('您还没有进行激活，请前去激活账户')
            return redirect(url_for('user.again_active'))
        elif not u.check_password(form.userpass.data):
            flash('请输入正确的用户名或密码')
        else:
            flash('登录成功')
            # 修改登录时间
            u.lastLogin = datetime.now()
            u.save()
            login_user(u, remember=form.remember.data)  # 使用第三方扩展库处理登录状态的维持
            return redirect(url_for('main.index'))

    return render_template('user/login.html', form=form)


# 退出登录
@user.route('logout')
def logout():
    logout_user()
    flash('退出成功')
    return redirect(url_for('main.index'))

App/templates/common/base1.0.html
{% extends 'bootstrap/base.html' %}
{% block title %}
    boot_base
{% endblock %}
{% block styles %}
    {{ super() }}

<style>
    body{
        background-image: url("http://cdnonline.top/2003340.jpg");
    }
</style>
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" style="margin: 0">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index',_external=True) }}">
                    <span class="glyphicon glyphicon-grain" aria-hidden="true"></span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('main.index',_external=True) }}">首页 <span class="sr-only">(current)</span></a>
                    </li>
                    <li><a href="{{ url_for('posts.send_posts',_external=True) }}">发表博客</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" action="{{ url_for('posts.search',_external=True ) }}" method="post">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="搜索" name="keyword" required>
                        </div>
                        <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                    {# 验证是否已经登录 #}
                    {% if  current_user.is_authenticated %}
                        <li><a href="#">欢迎：{{ current_user.username }}</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">个人中心<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('owncenter.user_info', _exrernal=True) }}" target="_blank" >查看与修改个人信息</a></li>
                                <li><a href="{{ url_for('owncenter.upload', _external=True) }}">上传头像</a></li>

                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('owncenter.posts_manager',_external=True) }}">博客管理</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ url_for('user.logout',_external=True) }}">退出登录</a></li>
                    {% else %}
                        <li><a href="{{ url_for('user.login',_external=True) }}">登录</a></li>
                        <li><a href="{{ url_for('user.register',_external=True) }}">注册</a></li>
                    {% endif %}

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block content %}
    <div class="container" style="width: 70%;">
        {# 配置消息闪现 #}
        {% for msg in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ msg }}</strong>
            </div>
        {% endfor %}
        {% block page_content %}
        {% endblock %}
    </div>

<footer>
    <p class="text-center">Design by Alone <a href="http://www.beian.miit.gov.cn/" style="color: orange">陕ICP备20001402号</a></p>
</footer>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh_CN') }}
<script src="{{ url_for('static',filename='editormd/examples/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='editormd/editormd.min.js') }}"></script>
<script type="text/javascript">
    $(function () {
        testEditor = editormd("test-editormd", {
            // width: "100%", 请不要添加
            height: 640,
            syncScrolling: "single",
            path: "{{ url_for('static',filename='editormd/lib/') }}",
            saveHTMLToTextarea : true,
            taskList: true,
            toc: true,
            tocm: true,
            imageUpload : true,
            imageFormats : [ "jpg", "jpeg", "gif", "png", "bmp", "webp" ],
            imageUploadURL : "{{ url_for('posts.upload_image') }}",
            emoji: true,//emoji表情，默认关闭

        })});
</script>

{% endblock %}

App/templates/common/page_macro.html
    {% macro page(pagination, endPoint) %}
    <nav class="text-center m-t-lg m-b-lg" role="navigation">
  <ul class="page-navigator">
  {# 如果没有上一页，显示无法点击 #}
    <li {% if not pagination.has_prev %}class="disabled" {% endif %} >
    {# 如果有上一页，就跳转到对应页码 #}
      <a {% if pagination.has_prev %}href="{{ url_for(endPoint, page=pagination.prev_num, **kwargs) }}"{% endif %}  aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>

  {% for p in pagination.iter_pages() %}
    <li {% if p==pagination.page %}class="current" {% endif %} >
        <a href="{{ url_for(endPoint, page=p, **kwargs) }}">{{ p }}</a>
    </li>
  {% endfor %}

    <li {% if not pagination.has_next %}class="disabled" {% endif %}>
      <a {% if pagination.has_next %}href="{{ url_for(endPoint, page=pagination.next_num, **kwargs) }}"{% endif %}  aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
    {% endmacro %}