App/models/posts.py
from App.extensions import db
from .db_base import DB_Base
from datetime import datetime

posts_categorys = db.Table('posts_categorys',
                       db.Column('posts_id', db.Integer, db.ForeignKey('posts.id'), primary_key=True),
                       db.Column('categorys_id', db.Integer, db.ForeignKey('categorys.id'), primary_key=True)
                       )
# 博客模型
class Posts(DB_Base, db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(20), index=True)  # 标题
    article = db.Column(db.Text)  # md格式正文
    pid = db.Column(db.Integer, default=0)  # 父id
    path = db.Column(db.Text, default='0,')  # 路径
    visit = db.Column(db.Integer, default=0)  # 文章访问量
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)  # 发表时间
    state = db.Column(db.Integer, default=0)  # 是否所有人可见
    img = db.Column(db.String(70))  # 图片

    tags = db.relationship('Categorys', secondary=posts_categorys, backref=db.backref('posts'))

    u_id = db.Column(db.Integer, db.ForeignKey('user.id'))  # 关联主表user的自增id



class Categorys(DB_Base, db.Model):
    __tablename__ = 'categorys'
    id = db.Column(db.Integer, primary_key=True)
    categorys = db.Column(db.String(20),index=True, unique=True)










App/forms/posts.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileAllowed, FileRequired, FileField
from App.extensions import file  # 导入文件上传配置对象


# 发表博客的表单类
class SendPosts(FlaskForm):
    title = StringField('标题', validators=[DataRequired('标题内容不能为空'),
                                          Length(min=3,max=100,message='标题内容在3-100字之间')],render_kw={'placeholder':'请输入标题'})
    article = TextAreaField('博客内容', validators=[DataRequired('博客内容不能为空')],render_kw={'placeholder':'请输入博客内容'})

    submit = SubmitField('发表博客')


# 发表评论和回复的表单类
class Comment(FlaskForm):
    article = TextAreaField('评论内容', validators=[DataRequired('评论内容不能为空')])
    submit = SubmitField('发表评论')


# 添加分类的表单
class Catgs(FlaskForm):
    categorys = StringField('分类专栏',
                            render_kw={'placeholder': '请输入分类'})

App/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from sqlalchemy import or_

from App.forms import SendPosts, Comment, Catgs  # 导入发表博客与发表评论的表单类
from App.models import Posts,Categorys,User # 导入博客模型类和标签模型类
from flask_login import current_user, login_required

from datetime import datetime
from flask import jsonify, request
from App.extensions import qiniu_store, csrf
import os, base64
from App.extensions import file
from PIL import Image

posts = Blueprint('posts', __name__)


# 使用uuid扩展库生成唯一的名称
def random_filename(suffix):
    import uuid
    u = uuid.uuid4()
    return str(u) + '.' + suffix


# 图片缩放处理
def img_zoom(path, width=1000, height=250):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    # img.thumbnail((width, height))
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


@posts.route('/send_posts/', methods=['GET', 'POST'])
def send_posts():
    form = SendPosts()
    ctgs = Categorys.query.all()
    # 判断登录后在进行发表
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再发表')
    if current_user.id==1:
        if form.validate_on_submit():
            # md格式
            article = request.form['article']
            ctgs = request.form['ctgs']
            tags = Categorys.query.filter_by(categorys=ctgs).first()
            # 图片上传
            img = request.files.get('img')  # 获取上传对象
            ex = os.path.splitext(img.filename)[1]
            filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
            file = img.stream.read()
            qiniu_store.save(file, filename)
            post = Posts(title=form.title.data, user=current_user, article=article, img=qiniu_store.url(filename),tags=[tags])
            post.save()
            flash('博客发表成功')
            return redirect(url_for('main.index'))
    else:
        flash('您没有发表博客的权限！')
        return redirect(url_for('main.index'))
    return render_template('posts/send_posts.html', form=form, ctgs=ctgs)


# 增加分类
@posts.route('/add_catgs/', methods=['GET', 'POST'])
def add_catgs():
    form = Catgs()
    ctgs = Categorys.query.all()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        catgs = Categorys(categorys=form.categorys.data)
        catgs.save()
        print(form.categorys.data)
        flash('分类添加成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/add_categorys.html', form=form, ctgs=ctgs)


# 删除分类
@posts.route('/delete_catgs/', methods=['GET', 'POST'])
def delete_catgs():
    ctgs = Categorys.query.all()
    form = Catgs()
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后再操作')
    elif form.validate_on_submit():
        cs = request.form['ctgs']
        d = Categorys.query.filter_by(categorys=cs)[0]
        d.delete()
        flash('分类删除成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/delete_categorys.html', form=form, ctgs=ctgs)


# 搜索
@posts.route('/search/', methods=['GET', 'POST'])
@csrf.exempt
def search():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    # 获取搜索的关键字
    if request.method == 'POST':
        keyword = request.form.get('keyword', '')
    else:
        keyword = request.args.get('keyword', '')
    # 查询pid为0（是博客内容，不为0则是评论或回复内容），statue为0（所有人可见），按照时间降序显示
    # 搜索功能，搜索内容为：标题或正文
    pagination = Posts.query.filter(or_(Posts.title.contains(keyword), Posts.article.contains(keyword)), Posts.pid == 0,
                                    Posts.state == 0) \
        .order_by(Posts.timestamp.desc()) \
        .paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
    data = pagination.items  # 获取page页面的数据
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]
    return render_template('posts/search_detail.html', pagination=pagination, posts=data, keyword=keyword,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客分类
@posts.route('posts_ctgs',methods=['GET','POST'])
def posts_ctgs():
    try:
        page = int(request.args.get('page'))
    except:
        page = 1
    cid = request.args.get('pid')
    global pagination,data
    posts = Categorys.query.get(cid)
    for i in posts.posts:
        pagination = Posts.query.filter(Posts.title==i.title).order_by(Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)  # False 为不抛出异常
        data = pagination.items  # 获取page页面的数据
    category = Categorys.query.get(cid)
    # 将文章(pid=0)对应的的id查询出来，
    art = Posts.query.filter(Posts.pid==0).count()
    # 按照访问量排行降序查询，拿出前五
    visit = Posts.query.filter(Posts.pid == 0, Posts.state == 0).order_by(-Posts.visit)[:5]
    # 拿到文章对象，进行遍历，然后将访问量放进数组，进行求和
    article_list = Posts.query.filter(Posts.pid==0)
    list = []
    for i in article_list:
        list.append(i.visit)
    v=sum(list)

    cs = Categorys.query.all()
    comments_five = Posts.query.filter(Posts.pid!=0)[0:5]

    return render_template('posts/posts_ctgs.html',pagination=pagination,posts=data,category=category,art = art, visit=visit, v=v, ctgs=cs,comments_five=comments_five)


# 博客详情
@posts.route('/posts_detail/<int:pid>/')
def posts_detail(pid):
    # 查询当前博客的内容 pid为博客的自增id 并不是博客模型字段的pid
    p = Posts.query.get(pid)
    p.visit += 1  # 博客的访问量
    p.save()
    form = Comment()  # 发表评论和回复的表单类
    # 查询出博客的评论内容和回复，按照博客内容和回复在一起的排序顺序，
    # 过滤条件为博客path中包含博客id的，这样博客就将博客的内容过滤出去，只查询评论和留言
    comment = Posts.query.filter(Posts.path.contains(str(pid))).order_by(Posts.path.concat(Posts.id))
    ctgs = Categorys.query.all()
    comment_nums = Posts.query.filter(Posts.path.contains(str(pid))).count()

    return render_template('posts/posts_detail.html', posts=p, form=form, comment=comment, ctgs=ctgs, comment_nums=comment_nums)


# 评论和回复
@posts.route('/comment/', methods=['GET', 'POST'])
@login_required
def comment():
    pid = request.form.get('pid')
    rid = request.form.get('rid')
    # 判断当前是评论还是回复，如果为评论则为假，否则为真
    if rid:
        id = rid
    else:
        id = pid
    p = Posts.query.get(int(id))
    Posts(article=request.form.get('article'), pid=id, path=p.path + id + ',', user=current_user).save()

    return redirect(url_for('posts.posts_detail', pid=pid))


# editor.md的图片上传
@posts.route('/upload_image/', methods=['POST'])
@login_required
@csrf.exempt
def upload_image():
    data = request.files.get('editormd-image-file')
    if not data:
        res = {
            'success': 0,
            'message': '图片失败请重试'
        }
    else:
        ex = os.path.splitext(data.filename)[1]
        filename = datetime.now().strftime('%Y%m%d%H%M%S') + ex
        file = data.stream.read()
        qiniu_store.save(file, filename)
        res = {
            'success': 1,
            'message': '图片上传成功',
            'url': qiniu_store.url(filename)
        }
    return jsonify(res)

App/templates/posts/1.html
{% extends 'common/base1.0.html' %}
{% block title %}
    搜索...
{% endblock %}

{% block page_content %}
    <h1>搜索关键字“<font style="color: red">{{ keyword }}</font>”的结果为</h1>
    <br>
    {# 博客内容的展示 #}
    {% for p in posts %}
    <div class="media" style="background-color: rgba(255,255,255,0.8);padding:6px 5px;border-radius: 10px;">
    <a href="{{ url_for('posts.posts_detail',pid=p.id, _external=True) }}" style="color: #000000;text-decoration: none">
        <div class="media-left media-middle">
               <img class="media-object" src="{{ url_for('static',filename='upload/'+p.img) }}" alt="..."   style="border-radius: 5px;border-top:2px solid #ccc;border-right:2px solid #ccc;">
        </div>
        <div class="media-body">
            <h4 class="media-heading" style="font-weight: bold">{{ p.title }}</h4>
            <span style="font-size: 18px;">{{ p.article|striptags|showEllipsis }}</span>
        </div>
                    <br>

            <div style="float: right;color: black;font-size: 15px">
                <b>👍:{{ p.visit }}</b>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {{moment(p.timestamp).format('YYYY-MM-DD H:m:s')}}
            </div>
        <hr>
    </a>
    </div>
        {% endfor %}
    {# 分页 #}
    {% from 'common/page_macro.html' import page %}
    {{ page(pagination, 'posts.search',keyword=keyword) }}
{% endblock %}

App/templates/posts/add_categorys.html
{% extends 'common/base1.0.html' %}
{% block title %}
    发表博客
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
{% endblock %}

{% block scripts %}
    {{ super() }}

{% endblock %}
{% block page_content %}
    <div style="background-color: rgba(255,255,255,0.5);padding: 5px 3px">
<h2 class="page-header">增加分类</h2>
    <form action="" method="post">
        {{ form.csrf_token }}

            {{ form.categorys.label(style='font-size:16px;') }}
    &nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-success" href=''>+</button>
        {{ form.categorys(class="form-control") }}
        <div class="checkbox" style="position: relative;left: 20px">
            {% for ctg in ctgs %}
            <label >
                <input type="checkbox" style="height: 20px" name="ctgs" value="{{ ctg.categorys }}"><font style="font-size: 20px">{{ ctg.categorys }} </font>
            </label>
            {% endfor %}
        </div>
        {% for err in form.categorys.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>

    </form>
    </div>
{% endblock %}

App/templates/posts/delete_categorys.html
{% extends 'common/base1.0.html' %}
{% block title %}
    发表博客
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
{% endblock %}

{% block scripts %}
    {{ super() }}

{% endblock %}
{% block page_content %}
    <div style="background-color: rgba(255,255,255,0.5);padding: 5px 3px">
<h2 class="page-header">删除分类</h2>
    <form action="" method="post">
        {{ form.csrf_token }}

            {{ form.categorys.label(style='font-size:16px;') }}
    &nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-danger" href=''>-</button>
        <div class="checkbox" style="position: relative;left: 20px">
            {% for ctg in ctgs %}
            <label >
                <input type="checkbox" style="height: 20px" name="ctgs" value="{{ ctg.categorys }}"><font style="font-size: 20px">{{ ctg.categorys }} </font>
            </label>
            {% endfor %}
        </div>
        {% for err in form.categorys.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>

    </form>
    </div>
{% endblock %}

App/templates/posts/send_posts.html
{% extends 'common/base1.0.html' %}
{% block title %}
    发表博客
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
{% endblock %}

{% block scripts %}
    {{ super() }}

{% endblock %}
{% block page_content %}
    <div style="background-color: rgba(255,255,255,0.5);padding: 5px 3px">
<h2 class="page-header">发表博客</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
    {# 标题 #}
        {{ form.title.label(style='font-size:16px;') }}
        {{ form.title(class='form-control') }}
        {% for err in form.title.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
    <br>
    {# 分类 #}
    <div>
       <P> <font style="font-size: 20px">分类</font> &nbsp;&nbsp;&nbsp;<a type="submit" class="btn btn-success" href="{{ url_for('posts.add_catgs', _exrernal=True) }}">添加</a>
           <a type="submit" class="btn btn-danger" href="{{ url_for('posts.delete_catgs', _exrernal=True) }}">删除</a>
    &nbsp;&nbsp;&nbsp;</P>


        <div class="checkbox" style="position: relative;left: 20px">
            {% for ctg in ctgs %}
            <label >
                <input type="checkbox" style="height: 20px" name="ctgs" value="{{ ctg.categorys }}"><font style="font-size: 20px">{{ ctg.categorys }} </font>
            </label>
            {% endfor %}
        </div>

    </div>
{# 图片上传 #}
<div>
    <hr>
        图片上传：<input type="file" name="img" required>
    <br>
</div>
    <br>
    {# 正文 #}
        {{ form.article.label(style='font-size:16px;') }}
        <div id="test-editormd" class="editormd">
        {{ form.article(style="display:none;") }}
        </div>


        {% for err in form.article.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">发表</button>
    </form>
    </div>
{% endblock %}